#!/usr/bin/env node

/**
 * Seed the `blueprint_sections` Firestore collection from
 * scripts/blueprint_sections_seed.json (generated by
 * `flutter test scripts/export_blueprint_sections.dart`).
 *
 * One-time (or re-run-to-update) migration: Blueprint section/question
 * content used to be hardcoded in
 * lib/features/blueprints/data/blueprint_mock_data.dart. The app now reads
 * it from Firestore (see blueprint_repository.dart) so content can be
 * edited without an app release; that file remains the seed source and an
 * offline/pre-seed fallback.
 *
 * Usage:
 *   1. flutter test scripts/export_blueprint_sections.dart
 *   2. cd scripts && npm install firebase-admin
 *   3. node seed_blueprint_sections.js
 *
 * Requirements: a service account key with Firestore write access.
 *   - Either set GOOGLE_APPLICATION_CREDENTIALS to a service account JSON
 *     path, or run via `gcloud auth application-default login` first.
 *   - Project id: pass --project=<id> or set FIREBASE_PROJECT_ID env var
 *     (defaults to the id in ../.firebaserc).
 */

const fs = require('fs');
const path = require('path');
const admin = require('firebase-admin');

const SEED_PATH = path.resolve(__dirname, 'blueprint_sections_seed.json');

function resolveProjectId() {
  const arg = process.argv.find((a) => a.startsWith('--project='));
  if (arg) return arg.split('=')[1];
  if (process.env.FIREBASE_PROJECT_ID) return process.env.FIREBASE_PROJECT_ID;
  const rcPath = path.resolve(__dirname, '../.firebaserc');
  const rc = JSON.parse(fs.readFileSync(rcPath, 'utf8'));
  return rc.projects && rc.projects.default;
}

async function main() {
  if (!fs.existsSync(SEED_PATH)) {
    console.error(
      `Seed file not found: ${SEED_PATH}\n` +
        'Run `flutter test scripts/export_blueprint_sections.dart` first.',
    );
    process.exit(1);
  }

  const projectId = resolveProjectId();
  admin.initializeApp({
    credential: admin.credential.applicationDefault(),
    projectId,
  });
  const db = admin.firestore();

  const sections = JSON.parse(fs.readFileSync(SEED_PATH, 'utf8'));
  console.log(`Seeding ${sections.length} sections into project "${projectId}"...`);

  const batch = db.batch();
  for (const section of sections) {
    const { id, ...data } = section;
    batch.set(db.collection('blueprint_sections').doc(id), data);
  }
  await batch.commit();

  console.log(`Done. Wrote ${sections.length} docs to blueprint_sections/.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
